/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AppointmentDAO;
import dao.AppointmentDAO;
import service.BillingService;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pawan
 */
public class BillingFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillingFrame.class.getName());
    private BillingService billingService;
    private AppointmentDAO appointmentDAO;

    private int currentTreatmentId;
    private String currentAppointmentNumber;
    /**
     * Creates new form BillingFrame
     */
    public BillingFrame() {
        initComponents();
        
        billingService = new BillingService();
        appointmentDAO = new AppointmentDAO();

        loadAppointmentNumbers();

        lblPatientName.setText("-");
        lblDentistName.setText("-");
        lblTotalAmount.setText("Rs. 0.00");

        DefaultTableModel model =
                (DefaultTableModel) tblBilling.getModel();

        model.setRowCount(0);



        clearBillingTable();
        
            // 1. Cards සහ Strips වල Edges Curved/Rounded කිරීම
        cardAppointment.putClientProperty("JComponent.roundRect", true);
        cardPatientInfo.putClientProperty("JComponent.roundRect", true);
        jPanel1.putClientProperty("JComponent.roundRect", true);
        cardInvoice.putClientProperty("JComponent.roundRect", true);
        pnlTotalStrip.putClientProperty("JComponent.roundRect", true);

        // 2. ComboBox & Buttons Rounded Style කිරීම
        cmbAppointment.putClientProperty("JComponent.roundRect", true);
        btnLoad.putClientProperty("JButton.buttonType", "square");
        btnCalculate.putClientProperty("JButton.buttonType", "roundRect");
        btnPrintReceipt.putClientProperty("JButton.buttonType", "roundRect");

        // 3. Table Header එක නිල් පාට කර Flat පෙනුම ලබා දීම
        tblBilling.getTableHeader().setOpaque(false);
        tblBilling.getTableHeader().setBackground(new java.awt.Color(0, 86, 210));
        tblBilling.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblBilling.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tblBilling.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));

        // 4. Table Background එක සුදු පැහැ කිරීම
        spBillingTable.getViewport().setBackground(java.awt.Color.WHITE);
    }

/**
 * Loads all appointment numbers into the
 * appointment combo box.
 */
private void loadAppointmentNumbers() {

    cmbAppointment.removeAllItems();

    cmbAppointment.addItem(
            "Select Appointment Number"
    );

    String[] appointmentNumbers =
            appointmentDAO.getAllAppointmentNumbers();

    for (String number : appointmentNumbers) {

        cmbAppointment.addItem(number);
    }
}


    
    private void clearBillingTable() {

    DefaultTableModel model =
            (DefaultTableModel) tblBilling.getModel();

    model.setRowCount(0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BillingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardAppointment = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbAppointment = new javax.swing.JComboBox<>();
        btnLoad = new javax.swing.JButton();
        cardPatientInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDentistName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        cardInvoice = new javax.swing.JPanel();
        spBillingTable = new javax.swing.JScrollPane();
        tblBilling = new javax.swing.JTable();
        pnlTotalStrip = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnPrintReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BillingPanel.setPreferredSize(new java.awt.Dimension(940, 620));
        BillingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 43, 72));
        jLabel1.setText("BILLING SYSTEM");
        jLabel1.setPreferredSize(new java.awt.Dimension(450, 30));
        BillingPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 450, 30));

        jLabel2.setForeground(new java.awt.Color(100, 116, 139));
        jLabel2.setText("Generate invoice and manage payments");
        BillingPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 350, 20));

        cardAppointment.setBackground(new java.awt.Color(255, 255, 255));
        cardAppointment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 43, 72));
        jLabel3.setText("Appointment No");
        cardAppointment.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 12, 180, 18));

        cmbAppointment.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmbAppointment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SeleCt Appoinment Number" }));
        cardAppointment.add(cmbAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 35, 320, 40));

        btnLoad.setBackground(new java.awt.Color(0, 122, 255));
        btnLoad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLoad.setForeground(new java.awt.Color(255, 255, 255));
        btnLoad.setText("LOAD DETAILS");
        btnLoad.setBorderPainted(false);
        btnLoad.setFocusPainted(false);
        btnLoad.addActionListener(this::btnLoadActionPerformed);
        cardAppointment.add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 35, 160, 40));

        BillingPanel.add(cardAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 880, 90));

        cardPatientInfo.setBackground(new java.awt.Color(255, 255, 255));
        cardPatientInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 243, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 86, 210));
        jLabel4.setText("PATIENT INFORMATION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 200, 18));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(55, 65, 81));
        jLabel5.setText("Patient");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 38, 60, 20));

        jSeparator1.setForeground(new java.awt.Color(203, 213, 225));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 36, 2, 22));

        lblDentistName.setForeground(new java.awt.Color(17, 24, 39));
        lblDentistName.setText("Dr. Silva");
        jPanel1.add(lblDentistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 38, 180, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(55, 65, 81));
        jLabel6.setText("Dentist");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 38, 60, 20));

        lblPatientName.setForeground(new java.awt.Color(17, 24, 39));
        lblPatientName.setText("Kasun Perera");
        jPanel1.add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 38, 180, 20));

        cardPatientInfo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 70));

        BillingPanel.add(cardPatientInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 880, 90));

        cardInvoice.setBackground(new java.awt.Color(255, 255, 255));
        cardInvoice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spBillingTable.setBorder(null);

        tblBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "DESCRIPTION", "AMOUNT"
            }
        ));
        tblBilling.setRowHeight(32);
        tblBilling.setSelectionBackground(new java.awt.Color(235, 243, 255));
        spBillingTable.setViewportView(tblBilling);

        cardInvoice.add(spBillingTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 135));

        pnlTotalStrip.setBackground(new java.awt.Color(232, 248, 238));
        pnlTotalStrip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(5, 122, 85));
        jLabel7.setText("TOTAL");
        pnlTotalStrip.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 100, 20));

        lblTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(5, 122, 85));
        lblTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalAmount.setText("Rs. 7,000.00");
        pnlTotalStrip.add(lblTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 160, 24));

        cardInvoice.add(pnlTotalStrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 860, 45));

        btnCalculate.setBackground(new java.awt.Color(0, 154, 73));
        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("CALCULATE");
        btnCalculate.setBorderPainted(false);
        btnCalculate.setFocusPainted(false);
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);
        cardInvoice.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 225, 170, 44));

        btnPrintReceipt.setBackground(new java.awt.Color(79, 70, 229));
        btnPrintReceipt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnPrintReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintReceipt.setText("PRINT RECEIPT");
        btnPrintReceipt.setBorderPainted(false);
        btnPrintReceipt.setFocusPainted(false);
        btnPrintReceipt.addActionListener(this::btnPrintReceiptActionPerformed);
        cardInvoice.add(btnPrintReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 225, 180, 44));

        BillingPanel.add(cardInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 285, 880, 290));

        getContentPane().add(BillingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
            // Check whether an appointment is selected
    if (cmbAppointment.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select an appointment number.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // Get selected appointment number
    String appointmentNumber =
            cmbAppointment.getSelectedItem().toString();

    try {

        // Get appointment details through service layer
        ResultSet rs =
                billingService.getAppointmentDetails(
                        appointmentNumber
                );

        if (rs != null && rs.next()) {

            // Store appointment number
            currentAppointmentNumber =
                    rs.getString("appointment_number");

            // Display patient name
            lblPatientName.setText(
                    rs.getString("patient_name")
            );

            // Display dentist name
            lblDentistName.setText(
                    rs.getString("dentist_name")
            );

            // Get treatment ID
            currentTreatmentId =
                    rs.getInt("treatment_id");

            // Get table model
            DefaultTableModel model =
                    (DefaultTableModel)
                            tblBilling.getModel();

            // Remove previous billing details
            model.setRowCount(0);

            // Get treatment name
            String treatmentName =
                    billingService.getTreatmentName(
                            currentTreatmentId
                    );

            // Get treatment fee
            double treatmentFee =
                    billingService.getTreatmentFee(
                            currentTreatmentId
                    );

            // Get consultation fee
            double consultationFee =
                    billingService.getConsultationFee();

            // Add consultation fee to table
            model.addRow(
                    new Object[]{
                        "Consultation Fee",
                        String.format(
                                "Rs. %.2f",
                                consultationFee
                        )
                    }
            );

            // Add treatment to table
            model.addRow(
                    new Object[]{
                        treatmentName,
                        String.format(
                                "Rs. %.2f",
                                treatmentFee
                        )
                    }
            );

            // Calculate total amount
            double total =
                    billingService.calculateTotal(
                            consultationFee,
                            treatmentFee
                    );

            // Display total
            lblTotalAmount.setText(
                    String.format(
                            "Rs. %.2f",
                            total
                    )
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Appointment details not found.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error loading appointment details:\n"
                + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
        );

        e.printStackTrace();
    }
        
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
            // Check whether an appointment has been loaded
    if (currentAppointmentNumber == null) {

        JOptionPane.showMessageDialog(
                this,
                "Please load an appointment first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // Get consultation fee
    double consultationFee =
            billingService.getConsultationFee();

    // Get treatment fee
    double treatmentFee =
            billingService.getTreatmentFee(
                    currentTreatmentId
            );

    // Calculate total amount
    double total =
            billingService.calculateTotal(
                    consultationFee,
                    treatmentFee
            );

    // Display total amount
    lblTotalAmount.setText(
            String.format(
                    "Rs. %.2f",
                    total
            )
    );

    // Show success message
    JOptionPane.showMessageDialog(
            this,
            "Bill calculated successfully.",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed
        // TODO add your handling code here:
            // Check whether an appointment has been loaded
               // Check whether an appointment has been loaded
    if (currentAppointmentNumber == null) {

        JOptionPane.showMessageDialog(
                this,
                "Please load an appointment first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        // Get consultation fee
        double consultationFee =
                billingService.getConsultationFee();

        // Get treatment fee
        double treatmentFee =
                billingService.getTreatmentFee(
                        currentTreatmentId
                );

        // Calculate total
        double total =
                billingService.calculateTotal(
                        consultationFee,
                        treatmentFee
                );

        // Save bill to database
        boolean saved =
                billingService.saveBill(
                        currentAppointmentNumber,
                        consultationFee,
                        treatmentFee
                );

        // Create receipt text
        String receipt =
                "========================================\n"
                + "          SUNRISE DENTAL CLINIC\n"
                + "              BILL RECEIPT\n"
                + "========================================\n\n"
                + "Appointment No : "
                + currentAppointmentNumber + "\n"
                + "Patient        : "
                + lblPatientName.getText() + "\n"
                + "Dentist        : "
                + lblDentistName.getText() + "\n\n"
                + "----------------------------------------\n"
                + String.format(
                        "%-25s Rs. %8.2f%n",
                        "Consultation Fee",
                        consultationFee
                )
                + String.format(
                        "%-25s Rs. %8.2f%n",
                        "Treatment",
                        treatmentFee
                )
                + "----------------------------------------\n"
                + String.format(
                        "%-25s Rs. %8.2f%n",
                        "TOTAL",
                        total
                )
                + "----------------------------------------\n\n"
                + "        Thank you for visiting us!\n"
                + "========================================";

        // Display receipt
        JTextArea receiptArea =
                new JTextArea(receipt);

        receiptArea.setFont(
                new java.awt.Font(
                        "Monospaced",
                        java.awt.Font.PLAIN,
                        12
                )
        );

        receiptArea.setEditable(false);

        // Show receipt preview
        int option =
                JOptionPane.showConfirmDialog(
                        this,
                        new JScrollPane(receiptArea),
                        "Receipt Preview",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.PLAIN_MESSAGE
                );

        // Print only when user clicks OK
        if (option == JOptionPane.OK_OPTION) {

            boolean complete =
                    receiptArea.print();

            if (complete) {

                JOptionPane.showMessageDialog(
                        this,
                        "Receipt printed successfully.",
                        "Print Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Printing was cancelled.",
                        "Print Cancelled",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error while printing receipt:\n"
                + e.getMessage(),
                "Printing Error",
                JOptionPane.ERROR_MESSAGE
        );

        e.printStackTrace();
    }
 
    }//GEN-LAST:event_btnPrintReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BillingPanel;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JPanel cardAppointment;
    private javax.swing.JPanel cardInvoice;
    private javax.swing.JPanel cardPatientInfo;
    private javax.swing.JComboBox<String> cmbAppointment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDentistName;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JPanel pnlTotalStrip;
    private javax.swing.JScrollPane spBillingTable;
    private javax.swing.JTable tblBilling;
    // End of variables declaration//GEN-END:variables
}
