/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author pawan
 */
public class HelpFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HelpFrame.class.getName());

    /**
     * Creates new form HelpFrame
     */
    public HelpFrame() {
        initComponents();
        applyFlatLafStyles();
    }

    private void applyFlatLafStyles() {
    // 1. Modern Rounded Top Feature Cards
    String whiteCardStyle = "arc: 16; background: #FFFFFF; border: 1,1,1,1,#E2E8F0;";
    cardLogin.putClientProperty(FlatClientProperties.STYLE, whiteCardStyle);
    cardAppointment.putClientProperty(FlatClientProperties.STYLE, whiteCardStyle);
    cardSearch.putClientProperty(FlatClientProperties.STYLE, whiteCardStyle);
    cardBilling.putClientProperty(FlatClientProperties.STYLE, whiteCardStyle);

    // 2. Circular Icon Badges
    pnlIconLogin.putClientProperty(FlatClientProperties.STYLE, "arc: 999; background: #EBF3FF;");
    pnlNo.putClientProperty(FlatClientProperties.STYLE, "arc: 999; background: #E8F8EE;");
    pnlIconSearch.putClientProperty(FlatClientProperties.STYLE, "arc: 999; background: #F3E8FF;");
    pnlBilling.putClientProperty(FlatClientProperties.STYLE, "arc: 999; background: #FEF3C7;");

    // 3. Bottom Instruction Card
    cardInstructions.putClientProperty(FlatClientProperties.STYLE, "arc: 20; background: #EBF3FF; border: 1,1,1,1,#D0E2FF;");

    pnlinfo.putClientProperty(FlatClientProperties.STYLE, "arc: 999; ");

    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardLogin = new javax.swing.JPanel();
        pnlIconLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cardAppointment = new javax.swing.JPanel();
        pnlNo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cardSearch = new javax.swing.JPanel();
        pnlIconSearch = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cardBilling = new javax.swing.JPanel();
        pnlBilling = new javax.swing.JPanel();
        lblBilling = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardInstructions = new javax.swing.JPanel();
        pnlinfo = new javax.swing.JPanel();
        lblinfo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(940, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardLogin.setBackground(new java.awt.Color(255, 255, 255));
        cardLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIconLogin.setBackground(new java.awt.Color(235, 243, 255));
        pnlIconLogin.setLayout(new java.awt.GridLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8.png"))); // NOI18N
        pnlIconLogin.add(jLabel3);

        cardLogin.add(pnlIconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 60, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(15, 43, 72));
        jLabel7.setText("Login");
        cardLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 20));

        jLabel8.setForeground(new java.awt.Color(100, 116, 139));
        jLabel8.setText("How to login to the system securely.");
        cardLogin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 270, 20));

        jPanel1.add(cardLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 425, 90));

        cardAppointment.setBackground(new java.awt.Color(255, 255, 255));
        cardAppointment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNo.setBackground(new java.awt.Color(232, 248, 238));
        pnlNo.setLayout(new java.awt.GridLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon5.png"))); // NOI18N
        pnlNo.add(jLabel5);

        cardAppointment.add(pnlNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 60, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(15, 43, 72));
        jLabel11.setText("Appointment");
        cardAppointment.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 20));

        jLabel12.setForeground(new java.awt.Color(100, 116, 139));
        jLabel12.setText("How to register a new appointment.");
        cardAppointment.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 270, 20));

        jPanel1.add(cardAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 75, 425, 90));

        cardSearch.setBackground(new java.awt.Color(255, 255, 255));
        cardSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIconSearch.setBackground(new java.awt.Color(243, 232, 255));
        pnlIconSearch.setLayout(new java.awt.GridLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon6.png"))); // NOI18N
        pnlIconSearch.add(jLabel4);

        cardSearch.add(pnlIconSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 60, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(15, 43, 72));
        jLabel9.setText("Search");
        cardSearch.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 20));

        jLabel10.setForeground(new java.awt.Color(100, 116, 139));
        jLabel10.setText("Find and manage appointments easily.");
        cardSearch.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 270, 20));

        jPanel1.add(cardSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 425, 90));

        cardBilling.setBackground(new java.awt.Color(255, 255, 255));
        cardBilling.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBilling.setBackground(new java.awt.Color(254, 243, 199));
        pnlBilling.setLayout(new java.awt.GridLayout());

        lblBilling.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon7.png"))); // NOI18N
        pnlBilling.add(lblBilling);

        cardBilling.add(pnlBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 60, 60));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(15, 43, 72));
        jLabel13.setText("Billing");
        cardBilling.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 20));

        jLabel14.setForeground(new java.awt.Color(100, 116, 139));
        jLabel14.setText("Calculate and manage patient bills.");
        cardBilling.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 270, 20));

        jPanel1.add(cardBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 180, 425, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 43, 72));
        jLabel1.setText("HELP & USER GUIDE");
        jLabel1.setPreferredSize(new java.awt.Dimension(450, 30));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 450, 30));

        jLabel2.setForeground(new java.awt.Color(100, 116, 139));
        jLabel2.setText("Find help articles and step-by-step instructions");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 350, 20));

        cardInstructions.setBackground(new java.awt.Color(235, 243, 255));
        cardInstructions.setForeground(new java.awt.Color(30, 41, 59));
        cardInstructions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlinfo.setBackground(new java.awt.Color(0, 98, 224));
        pnlinfo.setLayout(new java.awt.GridLayout());

        lblinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info (1).png"))); // NOI18N
        pnlinfo.add(lblinfo);

        cardInstructions.add(pnlinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 26, 26));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel16.setText("Step-by-step instructions");
        cardInstructions.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 17, 300, 22));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 41, 59));
        jLabel17.setText("Login using authorized credentials.");
        cardInstructions.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 55, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(30, 41, 59));
        jLabel18.setText("Select Appointments from the sidebar.");
        cardInstructions.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(30, 41, 59));
        jLabel19.setText("Complete patient information accurately.");
        cardInstructions.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 145, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(30, 41, 59));
        jLabel20.setText("Select dentist and treatment for the appointment.");
        cardInstructions.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 190, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(30, 41, 59));
        jLabel21.setText("Save the appointment to confirm.");
        cardInstructions.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 235, -1, -1));

        jPanel1.add(cardInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 285, 880, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HelpFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardAppointment;
    private javax.swing.JPanel cardBilling;
    private javax.swing.JPanel cardInstructions;
    private javax.swing.JPanel cardLogin;
    private javax.swing.JPanel cardSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBilling;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JPanel pnlBilling;
    private javax.swing.JPanel pnlIconLogin;
    private javax.swing.JPanel pnlIconSearch;
    private javax.swing.JPanel pnlNo;
    private javax.swing.JPanel pnlinfo;
    // End of variables declaration//GEN-END:variables
}
