/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AppointmentDAO;

import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pawan
 */;
public class SearchFame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchFame.class.getName());
    private String selectedAppointmentNumber = null;
    /**
     * Creates new form SearchFame
     */
    public SearchFame() {
        initComponents();
        applyFlatLafStyles();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/user.png"));
        Image img = icon.getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH); // adjust
        jLabel5.setIcon(new ImageIcon(img));
       
        clearDetails();

    } 
    
    
    private void applyFlatLafStyles() {
    // 1. Rounded Card Panels
    cardSearch.putClientProperty("JComponent.roundRect", true);
    cardDetails.putClientProperty("JComponent.roundRect", true);

    // 2. Search Text Box Placeholder & Rounded Edge
    txtSearch.putClientProperty("JComponent.roundRect", true);
    txtSearch.putClientProperty("JTextField.placeholderText", "Enter appointment number (e.g. APT0001)");

    // 3. Rounded Buttons
    btnSearch.putClientProperty("JButton.buttonType", "square");
    btnSearch.putClientProperty("JButton.arc", 5);
    btnEdit.putClientProperty("JButton.buttonType", "roundRect");
    btnEdit.putClientProperty("JButton.arc", 5);
    btnDelete.putClientProperty("JButton.buttonType", "roundRect");
    btnDelete.putClientProperty("JButton.arc", 5);

}
    
    private void clearDetails() {

    lblNo.setText("-");
    lblPatient.setText("-");
    lblContact.setText("-");
    lblAddress.setText("-");
    lblDentist.setText("-");
    lblTreatment.setText("-");
    lbltime.setText("-");
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardSearch = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cardDetails = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblNo = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDentist = new javax.swing.JLabel();
        lblTreatment = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 43, 72));
        jLabel1.setText("APPOINTMENT SEARCH");
        jLabel1.setPreferredSize(new java.awt.Dimension(450, 30));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 450, 30));

        jLabel2.setForeground(new java.awt.Color(100, 116, 139));
        jLabel2.setText("Find patient details using appointment number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 350, 20));

        cardSearch.setBackground(new java.awt.Color(255, 255, 255));
        cardSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 43, 72));
        jLabel3.setText("Search Appointment");
        cardSearch.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 12, 200, 20));

        jLabel4.setForeground(new java.awt.Color(71, 85, 105));
        jLabel4.setText("Appointment Number");
        cardSearch.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 38, 180, 18));

        txtSearch.setBackground(new java.awt.Color(248, 250, 252));
        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 232, 240), 1, true));
        cardSearch.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 58, 460, 38));

        btnSearch.setBackground(new java.awt.Color(0, 122, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH ");
        btnSearch.setBorderPainted(false);
        btnSearch.setFocusPainted(false);
        btnSearch.setIconTextGap(3);
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        cardSearch.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 58, 130, 38));

        jPanel1.add(cardSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 880, 110));

        cardDetails.setBackground(new java.awt.Color(255, 255, 255));
        cardDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(153, 204, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jLabel5.setToolTipText("");
        cardDetails.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 28, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(15, 43, 72));
        jLabel6.setText("PATIENT DETAILS");
        cardDetails.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 18, 200, 22));
        cardDetails.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 277, 20, -1));

        jLabel8.setForeground(new java.awt.Color(71, 85, 105));
        jLabel8.setText("Date & Time");
        cardDetails.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 277, 180, -1));

        jLabel9.setText(":");
        cardDetails.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 277, 15, -1));
        cardDetails.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 277, 500, -1));
        cardDetails.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, 20, -1));

        jLabel12.setForeground(new java.awt.Color(71, 85, 105));
        jLabel12.setText("Appointment No");
        cardDetails.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 55, 180, -1));

        jLabel13.setText(":");
        cardDetails.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 55, 15, -1));
        cardDetails.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 92, 20, -1));

        jLabel16.setForeground(new java.awt.Color(71, 85, 105));
        jLabel16.setText("Patient Name");
        cardDetails.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 92, 180, -1));

        jLabel17.setText(":");
        cardDetails.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 92, 15, -1));
        cardDetails.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 129, 20, -1));

        jLabel20.setForeground(new java.awt.Color(71, 85, 105));
        jLabel20.setText("Contact");
        cardDetails.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 129, 180, -1));

        jLabel21.setText(":");
        cardDetails.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 129, 15, -1));
        cardDetails.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 166, 20, -1));

        jLabel25.setForeground(new java.awt.Color(71, 85, 105));
        jLabel25.setText("Address");
        cardDetails.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 166, 180, -1));

        jLabel26.setText(":");
        cardDetails.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 166, 15, -1));
        cardDetails.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, 20, -1));

        jLabel29.setForeground(new java.awt.Color(71, 85, 105));
        jLabel29.setText("Dentist");
        cardDetails.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 203, 180, -1));

        jLabel30.setText(":");
        cardDetails.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 203, 15, -1));
        cardDetails.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 20, -1));

        jLabel36.setForeground(new java.awt.Color(71, 85, 105));
        jLabel36.setText("Treatment");
        cardDetails.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 180, -1));

        jLabel38.setText(":");
        cardDetails.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 15, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        cardDetails.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 830, 1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 232)));
        cardDetails.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 830, 1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        cardDetails.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 159, 830, 1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        cardDetails.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 196, 830, 1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        cardDetails.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 233, 830, 1));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        cardDetails.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 270, 830, 1));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        cardDetails.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 307, 830, 1));

        btnEdit.setBackground(new java.awt.Color(0, 98, 224));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("UPDATE");
        btnEdit.setBorderPainted(false);
        btnEdit.setFocusPainted(false);
        btnEdit.addActionListener(this::btnEditActionPerformed);
        cardDetails.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 130, 40));

        btnDelete.setBackground(new java.awt.Color(225, 29, 72));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.setBorderPainted(false);
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        cardDetails.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 130, 40));

        lblNo.setText("jLabel10");
        cardDetails.add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 280, -1));

        lblPatient.setText("jLabel14");
        cardDetails.add(lblPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 95, 280, -1));

        lblContact.setText("jLabel18");
        cardDetails.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 134, 280, -1));

        lblAddress.setText("jLabel22");
        cardDetails.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 280, -1));

        lblDentist.setText("jLabel23");
        cardDetails.add(lblDentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 207, 280, -1));

        lblTreatment.setText("jLabel27");
        cardDetails.add(lblTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 245, 280, -1));
        cardDetails.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 140, 20));
        cardDetails.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 280, 70, 20));

        jPanel1.add(cardDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 880, 395));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String appointmentNumber = txtSearch.getText().trim();

        // Validate search field
        if (appointmentNumber.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter appointment number.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

            txtSearch.requestFocus();
            return;
        }

        AppointmentDAO dao = new AppointmentDAO();

        ResultSet rs = dao.searchAppointment(appointmentNumber);

        try {

            if (rs != null && rs.next()) {

                // Store selected appointment number
                selectedAppointmentNumber =
                        rs.getString("appointment_number");

                // Display appointment details
                lblNo.setText(
                        rs.getString("appointment_number")
                );

                lblPatient.setText(
                        rs.getString("patient_name")
                );

                lblContact.setText(
                        rs.getString("contact_number")
                );

                lblAddress.setText(
                        rs.getString("address")
                );

                lblDentist.setText(
                        rs.getString("dentist_name")
                );

                lblTreatment.setText(
                        rs.getString("treatment_name")
                );

                lblDate.setText(
                        rs.getString("appointment_date")
                );

                lblTime.setText(
                        rs.getString("appointment_time")
                );

            } else {

                clearDetails();

                JOptionPane.showMessageDialog(
                        this,
                        "Appointment not found.",
                        "Search Result",
                        JOptionPane.WARNING_MESSAGE
                );

                txtSearch.requestFocus();
            }

        } catch (Exception e) {

            e.printStackTrace();

            JOptionPane.showMessageDialog(
                    this,
                    "Error while searching appointment.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String appointmentNumber =lblNo.getText().trim();

        // No appointment selected
        if (appointmentNumber.equals("-")
            || appointmentNumber.isEmpty()) {

            JOptionPane.showMessageDialog(
                this,
                "Please search for an appointment first.",
                "Delete Appointment",
                JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Confirmation
        int result =
        JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete "
            + "appointment "
            + appointmentNumber
            + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (result != JOptionPane.YES_OPTION) {

            return;
        }

        AppointmentDAO dao =
        new AppointmentDAO();

        boolean deleted =
        dao.deleteAppointment(
            appointmentNumber
        );

        if (deleted) {

            JOptionPane.showMessageDialog(
                this,
                "Appointment deleted successfully.",
                "Delete Successful",
                JOptionPane.INFORMATION_MESSAGE
            );

            clearDetails();

            txtSearch.setText("");

            txtSearch.requestFocus();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Failed to delete appointment.",
                "Delete Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
            // Check whether an appointment has been selected
        if (selectedAppointmentNumber == null
                || selectedAppointmentNumber.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please search for an appointment first.",
                    "Update Appointment",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Open AppointmentFrame with selected appointment number
        AppoinmentFrame appointmentFrame = new AppoinmentFrame (selectedAppointmentNumber);

        appointmentFrame.setLocationRelativeTo(this);
        appointmentFrame.setVisible(true);

        // Close SearchFrame
        this.dispose();
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchFame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel cardDetails;
    private javax.swing.JPanel cardSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDentist;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTreatment;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
